/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cityScene.glb --transform 
Files: public/models/cityScene.glb [39.1MB] > /Users/ismailkhalil/Desktop/Personal/r3f-3rd-person-controller-starter/cityScene-transformed.glb [2.17MB] (94%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CityScene(props) {
  const { nodes, materials } = useGLTF("models/cityScene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[10.504, 6.263, 5.338]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.5, 0.56, 0.5]}
      >
        <mesh
          geometry={nodes.Cube033.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube033_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube033_2.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Cube033_3.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Cube033_4.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Cube033_5.geometry}
          material={materials.PaletteMaterial006}
        />
        <mesh
          geometry={nodes.Cube033_6.geometry}
          material={materials.PaletteMaterial007}
        />
      </group>
      <mesh
        geometry={nodes.House_1001.geometry}
        material={materials.PaletteMaterial008}
        position={[4.117, 8.998, -40.444]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.2, 1, 1]}
      />
      <mesh
        geometry={nodes.lsntern_mid.geometry}
        material={materials.PaletteMaterial009}
        position={[30.081, 4.622, 15.907]}
        rotation={[0, -1.571, 0]}
        scale={[0.558, 0.308, 0.558]}
      />
      <instancedMesh
        args={[nodes.Plane008.geometry, materials.PaletteMaterial007, 6]}
        instanceMatrix={nodes.Plane008.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Plane023.geometry, materials.PaletteMaterial007, 9999]}
        instanceMatrix={nodes.Plane023.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Plane025.geometry, materials.PaletteMaterial007, 10001]}
        instanceMatrix={nodes.Plane025.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Plane014.geometry, materials.PaletteMaterial007, 9996]}
        instanceMatrix={nodes.Plane014.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("models/cityScene-transformed.glb");
