/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/frame.glb -o Frame -T s 
Files: public/models/frame.glb [13.27KB] > /Users/ismailkhalil/Desktop/Personal/r3f-3rd-person-controller-starter/frame-transformed.glb [3.03KB] (77%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Frame(props) {
  const { nodes, materials } = useGLTF('models/frame-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shadeBeige001.geometry} material={nodes.shadeBeige001.material} position={[0.101, -0.566, 0.648]} rotation={[-1.61, 0.053, 1.616]} scale={1.446} />
    </group>
  )
}

useGLTF.preload('/models/frame-transformed.glb')
