/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/grassBlade.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("models/grassBlade.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.brush_Spikes_g0_b0.geometry}
        material={materials.brush_Spikes}
      />
    </group>
  );
}

useGLTF.preload("models/grassBlade.glb");
