/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Grass.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Grass.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_2.geometry} material={materials.Atlas} />
    </group>
  );
}

useGLTF.preload("/Grass.glb");
